// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGCMvd5GbdX895ytZZWr5twQq_9W2y0Hc',
    appId: '1:552131467227:web:f10c68a3a6e3bef81a39fe',
    messagingSenderId: '552131467227',
    projectId: 'callendarexam',
    authDomain: 'callendarexam.firebaseapp.com',
    storageBucket: 'callendarexam.firebasestorage.app',
    measurementId: 'G-M5YYVZPR7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sM7pjIxFlX8kmj8j0yua9m-MkeSfyDs',
    appId: '1:552131467227:android:731ea7abab8932511a39fe',
    messagingSenderId: '552131467227',
    projectId: 'callendarexam',
    storageBucket: 'callendarexam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCysiMaoayjygLrp-34WezTpBr029XzC1A',
    appId: '1:552131467227:ios:da07fa00cfab11dc1a39fe',
    messagingSenderId: '552131467227',
    projectId: 'callendarexam',
    storageBucket: 'callendarexam.firebasestorage.app',
    iosBundleId: 'com.example.flutterExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCysiMaoayjygLrp-34WezTpBr029XzC1A',
    appId: '1:552131467227:ios:da07fa00cfab11dc1a39fe',
    messagingSenderId: '552131467227',
    projectId: 'callendarexam',
    storageBucket: 'callendarexam.firebasestorage.app',
    iosBundleId: 'com.example.flutterExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGCMvd5GbdX895ytZZWr5twQq_9W2y0Hc',
    appId: '1:552131467227:web:d2ebfb62b2ac4eae1a39fe',
    messagingSenderId: '552131467227',
    projectId: 'callendarexam',
    authDomain: 'callendarexam.firebaseapp.com',
    storageBucket: 'callendarexam.firebasestorage.app',
    measurementId: 'G-D1LWKT6KEL',
  );

}